name: CI
on: [push]
jobs:
  build:
    name: Build and Deploy to Github Pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16.14.0']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      # - name: Lint
      #   run: yarn lint
      
      # - name: Test
      #   run: yarn test

      - name: Build
        run: yarn build

      - name: Build and deploy to storybook-static branch
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          # ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static
