name: CI
on:
  push:
    branches:
    - storybook-portfolio
    paths: ["stories/**"]

jobs:
  build-and-deploy:
    run-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build Storybook
      run: |
        npm install
        npm run build
    - name: Build and deploy to storybook-static branch
      uses: JamesIves/github-pages-deploy-action@4.3.3
      with:
        # ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: storybook-static